public/js/login.js, public/js/logout.js, public/js/signup.js, views/layouts/main.handlebars, views/signup.handlebars
updated handlebars and js for log in and signup, handlebars for homep…age, and js for logout.
=> handlesbars and js folders updated

package-lock.json, package.json
=> update package-lock and package.lock jsons

models/Cats.js, models/index.js
added some sequelize to make cats equalize
=> added cats.js and index.js

models/Cats.js, server.js
cats.js is connecting to server and seeding!
=> cats is seeding to server.

models/Dogs.js
this is just initial for seeding, will add later.               (Internet is out, will update soon)
=> added models/dogs.js initial

server.js, views/layouts/main.handlebars
seeding will update criteria for seeds tomorrow we are just trying to have a spot to to put the data.
=> connected server.js to dogs.js

package-lock.json, routes/api/infoDogs.js, server.js
added routes folder with appropriate index.js files
moved infoDogs.js into routes/api folder
corrected route paths for infoDogs.js
=> added routes folder and corrected the route paths for infoDogs.js

controllers/login.js, controllers/name.js, controllers/signup.js, models/Cats.js, models/Dogs.js, models/catnames.js, models/dogfacts.js, models/dognames.js, models/user.js, package.json, public/css/style.css, public/js/login.js, public/js/signup.js, seeds/female_dogs_name.js, seeds/index.js, seeds/male_dogs_name.js, server.js, views/homepage.handlebars
I set up the login page and signup page, that means that the user can login and signup on our site and I added the login button on the home page.
=> setup the login and signup page and add the login button to the home

models/dogfacts.js, public/js/dogQuestions.js
took out questions that didn't match the data so we can write the js tomorrow
=> modified questions

controllers/name.js, public/css/style.css, public/html/404page.html, public/js/name.js, views/name.handlebars
=> added the dogs and cats name to the page

seeds/dogbreeds.js, views/questions_dog.handlebars
finishing up question will pull again if someone wants to work on styling content
=> computer is buggin out i'm committing what i have before i restart.

controllers/questions.js, views/questions_cat.handlebars, views/questions_dog.handlebars
added some comments to Thor and fixed some styling. Will add more later. I am working on data next.
=> added comment to dog handlebars.

views/questions_dog.handlebars
=> added mixed breed group will add those to the data table next.

models/locations.js, server.js
added models/locations.js
hope it doesn't cause a "scruffle"
=> added models/locations.js

seeds/index.js, seeds/locations.js
added seeds/locations.js
added parks section to seeds/locations.js
=> added locations.js

seeds/locations.js
added bakery section to seeds/locations.js
=> added bakery section to seeds/locations.js

seeds/locations.js
added restaurants section to seeds/locations.js
=> added restaurants section to seeds/locations.js

seeds/locations.js
added hotel section to seeds/location.js
=> added hotel section to seeds/location.js

seeds/locations.js
added rescue section to seeds/location.js
=> added rescue section to seeds/location.js

seeds/locations.js
added dog beaches section to seeds/locations.js
=> added dog beaches section to seeds/locations.js

views/questions_cat.handlebars
updated cat handlebars questions 1 &2
=> updated question 1 & 2

views/questions_cat.handlebars
=> updated responses to each question

views/questions_cat.handlebars
=> updated questions responses and added question numbers

README.md
=> added beginning description for group to review before I write the rest

package-lock.json, package.json
=> added npm compression.
